name: "Publish Pre-Release to GitHub Packages"
on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Select Build Number'
        required: true
        type: number
env:
  TAG: build/${{ inputs.build }}
jobs:
  pre-release:
    name: "Publish Pre-Release to GitHub Packages"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Prepare Build
        run: |
          cp .github/workflows/pre-release/configuration.json configuration.json
          ./gradlew printVersion
          echo "VERSION=$(./gradlew printVersion -q)" >> $GITHUB_ENV
      - name: Publish Artifacts
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PUBLISH_USER: ${{ github.actor }}
          PUBLISH_VERSION: ${{ env.VERSION }}-pre${{ github.RUN_NUMBER }}+b${{ inputs.build }}
        run: |
          MODULES=("state" "compose" "navigation")
          for MODULE in "${MODULES[@]}"; do
            ./gradlew :${MODULE}:publishAllPublicationsToLulKrRepository
            echo
            echo
            sleep 5
          done
      - name: Create GitHub Pre-Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit ${{ env.TAG }} \
            --prerelease \
            -t "Pre-Release ${PUBLISH_VERSION}"